policies:
- name: cis-check-config-is-not-enabled
  resource: aws.account
  comment: |
    CIS AWS Foundations v1.4.0 (3.5)
  filters:
    — not:
      - type: check-config
        all-resources: true
        global-resources: true
        running: true
  mode:
    schedule: “rate(24 hours)”
    type: periodic
    execution-options:
      output_dir: s3://s3bucket/path/{account_id}/
    runtime: python3.8